/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus_placement_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author majma
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        buttonGroup1.add(male);
        buttonGroup1.add(female);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        batch = new javax.swing.JComboBox<>();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        mail = new javax.swing.JTextField();
        cpswd = new javax.swing.JPasswordField();
        pswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Register Page");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jToggleButton1.setText("Coordinator");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 30, 130, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 150, 20));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, 20));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel4.setText("Course & Batch");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 150, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel5.setText("Email ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 150, 20));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 150, 20));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 150, 20));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel9.setText("Confirm Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 150, 20));
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 290, 40));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 290, 40));
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 40));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 290, 40));

        batch.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        batch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));
        getContentPane().add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, 40));

        female.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        female.setText("Female");
        female.setOpaque(false);
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, -1));

        male.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        male.setText("Male");
        male.setToolTipText("Gender");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, -1));
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 290, 40));

        cpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpswdActionPerformed(evt);
            }
        });
        getContentPane().add(cpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 290, 40));

        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });
        getContentPane().add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 290, 40));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int windowClosed = 1;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        windowClosed = 0;
        this.dispose();
        new CRegisterPage().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void cpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpswdActionPerformed

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname1, sid1, uname1, phone1, pswd1, cpswd1, course1, batch1, gender="";
        gender = male.isSelected()?"Male":"Female";
        fname1 = fname.getText();
        sid1 = sid.getText();
        uname1 = mail.getText();
        phone1 = phone.getText();
        pswd1 = String.valueOf(pswd.getPassword());
        cpswd1 = String.valueOf(cpswd.getPassword());
        course1 = course.getText();
        batch1 = batch.getSelectedItem().toString();
        if(pswd1.equals(cpswd1)){
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
                Statement st = con.createStatement();
                st.executeUpdate("insert into student values('"+sid1+"','"+fname1+"','"+uname1+"','"+course1+"','"+batch1+"','"+gender+"','"+phone1+"','"+pswd1+"', '"+System.getProperty("user.dir")+"src//images//userico.png"+"', 'Null')");
                JOptionPane.showMessageDialog(fname, "Registration Successfull");
                fname.setText("");
                sid.setText("");
                phone.setText("");
                pswd.setText("");
                cpswd.setText("");
                course.setText("");
                mail.setText("");
                batch.setSelectedIndex(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(fname, "Registration Failed");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if(windowClosed == 1)
            new LoginPage().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> batch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField course;
    private javax.swing.JPasswordField cpswd;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JTextField sid;
    // End of variables declaration//GEN-END:variables
}
