/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus_placement_system;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author majma
 */
public class StudentInfo extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfo
     */
    
    public String zero(int inp){
        
        String res = "";
        if(inp < 10)
            res = "0"+String.valueOf(inp);
        else
            res = String.valueOf(inp);
        
        return res;
    }
    
    String path, sid, jobid, coname;
    String cord_mail, cord_name;
    public void getStrings(String[]STD, String cname, String cordname, String cordmail){
        try {
            BufferedImage img = ImageIO.read(new File(STD[6]));
            Image dimg = img.getScaledInstance(121, 142, Image.SCALE_SMOOTH);
            setico.setIcon(new ImageIcon(dimg));
        } catch (Exception e) {
            e.printStackTrace();
        }
        sname.setText(STD[0]);
        post.setText(STD[1]);
        course.setText(STD[2]);
        batch.setText(STD[3]);
        email.setText(STD[4]);
        phone.setText(STD[5]);
        path = STD[7];
        sid = STD[8];
        jobid = STD[9];
        coname = cname;
        cord_mail = cordmail;
        cord_name = cordname;
    }
    public StudentInfo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        setico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        post = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        batch = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Information");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setico.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(setico, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 41, 121, 142));

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setText("Student Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 205, 90, 28));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 205, 32, 28));

        sname.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 205, 278, 28));

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("Applied Post");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 247, 90, 28));

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 247, 32, 28));

        post.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 247, 278, 28));

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("Course");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 286, 90, 28));

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 286, 32, 28));

        course.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 286, 278, 28));

        batch.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 320, 278, 28));

        jLabel12.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel12.setText("Batch");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 320, 90, 28));

        jLabel13.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 320, 32, 28));

        email.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 354, 278, 28));

        jLabel15.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel15.setText("Email ID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 354, 90, 28));

        jLabel16.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 354, 32, 28));

        jLabel17.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel17.setText(":");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 388, 32, 28));

        phone.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 388, 278, 28));

        jLabel19.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel19.setText("Phone");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 388, 90, 28));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 434, 98, 43));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<html><body><center>Open<br/>Resume</center></body></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 434, 98, 43));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int inp = JOptionPane.showConfirmDialog(sname, "Are you sure to select "+sname.getText()+" as the "+post.getText(), "Please confirm again", 0, 1);
        if(inp == 0){
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
                Statement st = con.createStatement();
                
                int check = st.executeUpdate("insert into selectStudent values('"+sid+"','"+jobid+"')");
                if(check == 1){
                    JOptionPane.showMessageDialog(email, sname.getText()+" is selected for the job "+post.getText());
                    String MSG = "Dear "+sname.getText()+",<br/><br/>Congratulations. We are so happy to inform you that "+coname+" you like to extend the offer to you for the position of "+post.getText()+". After interviewing all the candidates, we found you the most suitable person for the job. You will be working directly under [supervisor name], and we believe that your addition to the team will add great value to the company.<br/><br/>Please feel free to reach out to me in case you have any other doubts. We look forward to you joining us and making us bigger and better than ever.<br/><br/>Yours’ sincerely,<br/>"+cord_name+"<br/>"+coname;
                    String date = "";
                    Date d = new Date();
                    date = zero(d.getDate())+"/"+zero(d.getMonth())+"/"+zero(d.getYear()+1900)+" "+zero(d.getHours())+":"+zero(d.getMinutes())+":"+zero(d.getSeconds());
                    st.executeUpdate("insert into srmail values('"+cord_mail+"','"+cord_name+"','"+email.getText()+"','C-S','"+MSG+"','"+date+"',0)");
                    st.executeUpdate("delete from appliedjobs where jobid='"+jobid+"' and sid='"+sid+"'");
                }else
                    JOptionPane.showMessageDialog(email, "DataBase Error");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Process p = Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+path);
			p.waitFor();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batch;
    private javax.swing.JLabel course;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel post;
    private javax.swing.JLabel setico;
    private javax.swing.JLabel sname;
    // End of variables declaration//GEN-END:variables
}
