/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campus_placement_system;


import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author majma
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserPage
     */
    public String pathAnalyzer(String inp){
        String[]str = inp.replace("\\", "/").split("/");
        String dat="";
        for(int i=0;i<str.length-1;i++){
            dat += str[i]+"\\\\";
        }
        dat += str[str.length-1];
        return dat;
    }
    
    public String convertTime(int hour, int minute, int second){
        String h=String.valueOf(hour), m=String.valueOf(minute), s=String.valueOf(second), n;
        if(hour>=12)
            n = "PM";
        else
            n = "AM";
        hour %= 12;
        h=String.valueOf(hour);
        if(hour<10)
            h = "0"+String.valueOf(hour);
        if(minute<10)
            m = "0"+String.valueOf(minute);
        if(second<10)
            s= "0"+String.valueOf(second);
        return h+":"+m+":"+s+" "+n;
    }
    
   
    public static String USRname = "sandeep@gmail.com", FNAME = "Sandeep S Rajesh", imgpath="C:\\Users\\majma\\Desktop\\Desk 003\\Campus_Placement_System\\src\\Uploads\\img1.png";
    public void getName(String name, String fullname, String ipath){
        USRname = name;
        FNAME = fullname;
        imgpath = ipath;
    }
    
    public UserPage() {
        initComponents();
        pset.hide();
        appjob.hide();
        searchjob.hide();
        SETDP.setIcon(new ImageIcon(getClass().getResource("/Images/userico.png")));
        new Thread(){
            public void run(){
                try {
                    while(true){
                        Date d = new Date();
                        settime.setText(convertTime(d.getHours(), d.getMinutes(), d.getSeconds()));
                        Thread.sleep(1000);
                    }
                } catch (Exception e) {
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SETDP = new javax.swing.JLabel();
        settime = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        searchjob = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pjob = new javax.swing.JTextField();
        pplace = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sal2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sal1 = new javax.swing.JTextField();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check1 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobdisp = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        appjob = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pset = new javax.swing.JPanel();
        profilepic = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        path = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        ch2 = new javax.swing.JCheckBox();
        ch3 = new javax.swing.JCheckBox();
        ch1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Page");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SETDP.setBackground(new java.awt.Color(255, 255, 255));
        SETDP.setOpaque(true);
        getContentPane().add(SETDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 45, 142, 148));

        settime.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        settime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settime.setText("00:00:00 AM");
        getContentPane().add(settime, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 170, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico12.jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 305, 180, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico13.jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 370, 180, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico14.jpg"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 498, 180, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico15.jpg"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 434, 180, 50));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico11.jpg"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 220, 180, 50));

        searchjob.setBackground(new java.awt.Color(255, 255, 255));
        searchjob.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel8.setText("  Preferred Job");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        pjob.setEditable(false);
        jPanel2.add(pjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 27, 170, 30));

        pplace.setEditable(false);
        jPanel2.add(pplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 27, 170, 30));

        jLabel9.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel9.setText("  Preferred Location");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 10, 110, 20));

        sal2.setEditable(false);
        jPanel2.add(sal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 27, 70, 30));

        jLabel10.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel10.setText("  Salary Range");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 110, 20));

        sal1.setEditable(false);
        jPanel2.add(sal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 27, 70, 30));

        check2.setBackground(new java.awt.Color(255, 255, 255));
        check2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        check2.setText("Select");
        check2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check2ItemStateChanged(evt);
            }
        });
        jPanel2.add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        check3.setBackground(new java.awt.Color(255, 255, 255));
        check3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        check3.setText("Select");
        check3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check3ItemStateChanged(evt);
            }
        });
        jPanel2.add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        check1.setBackground(new java.awt.Color(255, 255, 255));
        check1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        check1.setText("Select");
        check1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                check1ItemStateChanged(evt);
            }
        });
        check1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                check1StateChanged(evt);
            }
        });
        jPanel2.add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jButton9.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 110, 30));

        searchjob.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.white));
        jPanel3.setLayout(new java.awt.CardLayout());

        jobdisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jobdisp.setColumnSelectionAllowed(true);
        jobdisp.setRowHeight(110);
        jScrollPane2.setViewportView(jobdisp);
        jobdisp.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jobdisp.getColumnModel().getColumnCount() > 0) {
            jobdisp.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel3.add(jScrollPane2, "card2");

        searchjob.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 560, 210));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.black, java.awt.Color.white));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel11.setText("Job Id");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 30));

        jButton10.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jButton10.setText("Apply");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 13, 90, 50));

        searchjob.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 560, 80));

        getContentPane().add(searchjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 100, 580, 460));

        appjob.setBackground(new java.awt.Color(255, 255, 255));
        appjob.setLayout(new java.awt.CardLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Applications"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setRowHeight(80);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        appjob.add(jScrollPane1, "card2");

        getContentPane().add(appjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 100, 560, 450));

        pset.setBackground(new java.awt.Color(255, 255, 255));
        pset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilepic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pset.add(profilepic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 142, 148));

        jButton6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jButton6.setText("Upload");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pset.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 142, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Email ID");
        pset.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, -1));

        emailid.setEditable(false);
        pset.add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 30));

        phonenumber.setEditable(false);
        pset.add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Upload Resume");
        pset.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Confirm Password");
        pset.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Password");
        pset.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, -1));

        confirmpassword.setEditable(false);
        pset.add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 230, 30));

        password.setEditable(false);
        pset.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, 30));

        jButton7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jButton7.setText("Upload");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pset.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 142, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Phone Number");
        pset.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, -1));

        path.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        path.setForeground(new java.awt.Color(0, 153, 0));
        pset.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 160, 30));

        jButton8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 13)); // NOI18N
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        pset.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 70));

        ch2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch2ItemStateChanged(evt);
            }
        });
        pset.add(ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 294, -1, -1));

        ch3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch3ItemStateChanged(evt);
            }
        });
        pset.add(ch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 356, -1, -1));

        ch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch1ItemStateChanged(evt);
            }
        });
        pset.add(ch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 234, -1, -1));

        getContentPane().add(pset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 530, 460));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Welcome Muhammed Ajmal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/USER.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        pset.show();
        appjob.hide();
        searchjob.hide();
    }//GEN-LAST:event_jButton5ActionPerformed
JFileChooser fc2;
int checker2 = 0;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        fc2 = new JFileChooser();
        fc2.showOpenDialog(fc2);
        try {
            BufferedImage img = ImageIO.read(new File(fc2.getSelectedFile().toString()));
            Image dimg = img.getScaledInstance(142,148,Image.SCALE_SMOOTH);
            profilepic.setIcon(new ImageIcon(dimg));
            checker2 = 1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(fc2, "The selected file is not an image type", "Error", 2);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
JFileChooser fc;
int check = 0;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.showOpenDialog(fc);
        try {
            String P = fc.getSelectedFile().toString();
            if(P.endsWith("pdf")){
                check = 1;
                path.setText(P);
                
            }
            else
                throw new Exception("Not a pdf file");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(fc, "The selected file is not an image type", "Error", 2);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String pswd, cpswd, uname, resup, dpup;
        pswd = String.valueOf(password.getPassword());
        cpswd = String.valueOf(confirmpassword.getPassword());
        uname = emailid.getText();
        String dbquery = "";
        int sflag = 0;
        if(ch1.isSelected() && ch2.isSelected() && ch3.isSelected()){
            if(pswd.equals(cpswd)) {
                dbquery = "update student set uname='"+uname+"', phone='"+phonenumber.getText()+"', pswd='"+pswd+"'";
                sflag = 1;
            } else {
                JOptionPane.showMessageDialog(ch1, "Password doesn't match");
            }
            
        }else if(ch1.isSelected() && ch2.isSelected() && !ch3.isSelected()) {
            dbquery = "update student set uname='"+uname+"', phone='"+phonenumber.getText()+"'";
            sflag = 1;
        
        }else if(ch1.isSelected() && !ch2.isSelected() && ch3.isSelected()){
            if(pswd.equals(cpswd)) {
                dbquery = "update student set uname='"+uname+"', pswd='"+pswd+"'";;
                sflag = 1;
            } else {
                JOptionPane.showMessageDialog(ch1, "Password doesn't match");
            }
            
        }else if(!ch1.isSelected() && ch2.isSelected() && ch3.isSelected()){
            if(pswd.equals(cpswd)) {
                dbquery = "update student set phone='"+phonenumber.getText()+"', pswd='"+pswd+"'";
                sflag = 1;
            } else {
                JOptionPane.showMessageDialog(ch1, "Password doesn't match");
            }
            
        }else if(ch1.isSelected() && !ch2.isSelected() && !ch3.isSelected()){
            dbquery = "update student set uname='"+uname+"'";
            System.err.println(dbquery+" where uname='"+USRname+"'");
            sflag = 1;
        
        }else if(!ch1.isSelected() && ch3.isSelected() && !ch2.isSelected()){
            if(pswd.equals(cpswd)) {
                dbquery = "update student set pswd='"+pswd+"'";
                sflag = 1;
            } else {
                JOptionPane.showMessageDialog(ch1, "Password doesn't match");
            }
            
        }else if(!ch1.isSelected() && !ch3.isSelected() && ch2.isSelected()){
            dbquery = "update student set phone='"+phonenumber.getText()+"'";
            sflag = 1;
        }
        
        if(sflag == 1){
            System.err.println(dbquery+" where uname='"+USRname+"'");
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
                Statement st = con.createStatement();
                System.err.println(dbquery+" where uname='"+USRname+"'");
                st.executeUpdate(dbquery+" where uname='"+USRname+"'");
                JOptionPane.showMessageDialog(ch1, "Profile update successfull\nPlease login again.");
                this.dispose();
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(ch1, "Profile update unsuccessfull!");
            }
        }
        
        if(check == 1){
            try {
                Path fromFile = Paths.get(fc.getSelectedFile().toString());
                String path = System.getProperty("user.dir")+"\\src\\Uploads\\"+USRname.split("@")[0]+".pdf";
                Path toFile = Paths.get(path);
                try {
                    Files.deleteIfExists(Paths.get(path));
                }catch (Exception e) {
                    e.printStackTrace();
                }
                Files.copy(fromFile, toFile);
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
                Statement st = con.createStatement();
                st.executeUpdate("update student set rpath='"+pathAnalyzer(path)+"' where uname='"+USRname+"'");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        if(checker2 == 1){
            try {
                Path fromFile = Paths.get(fc2.getSelectedFile().toString());
                String path = System.getProperty("user.dir")+"\\src\\Uploads\\"+USRname.split("@")[0]+".jpg";
                Path toFile = Paths.get(path);
                try {
                    Files.deleteIfExists(Paths.get(path));
                }catch (Exception e) {
                    e.printStackTrace();
                }
                Files.copy(fromFile, toFile);
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
                Statement st = con.createStatement();
                st.executeUpdate("update student set path='"+pathAnalyzer(path)+"' where uname='"+USRname+"'");
                SETDP.setIcon(new ImageIcon(ImageIO.read(new File(path)).getScaledInstance(142, 148, Image.SCALE_SMOOTH)));
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }

        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pset.hide();
        appjob.show();
        searchjob.hide();
        try {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from vacancies where jobid in (select jobid from appliedjobs where sid=(select sid from student where uname='"+USRname+"'))");
            rs.next();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int count = Integer.parseInt(rs.getString("count(*)"));
            dtm.setRowCount(count);
            rs = st.executeQuery("select * from vacancies where jobid in (select jobid from appliedjobs where sid=(select sid from student where uname='"+USRname+"'))");
            count = 0;
            while(rs.next()){
                String tcon = "<html><body>"
                        +"<span style='color:#A3B0E4;font-size:11px;font-family:georgia;font-weight:bold;'>"+rs.getString("job")+"</span>"
                        
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Company: "+rs.getString("cname")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>"+rs.getString("address")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Salary: "+rs.getString("salary")+"</span>"
                        
                        + "</body></html>";
               jTable1.setValueAt(tcon, count, 0);

                count++;
            }
            
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchjob.show();
        pset.hide();
        appjob.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void check1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_check1StateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_check1StateChanged

    private void check1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check1ItemStateChanged
        // TODO add your handling code here:
        if(check1.isSelected())
            pjob.setEditable(true);
        else
            pjob.setEditable(false);
    }//GEN-LAST:event_check1ItemStateChanged

    private void check2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check2ItemStateChanged
        // TODO add your handling code here:
        if(check2.isSelected())
            pplace.setEditable(true);
        else
            pplace.setEditable(false);
    }//GEN-LAST:event_check2ItemStateChanged

    private void check3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_check3ItemStateChanged
        // TODO add your handling code here:
        if(check3.isSelected()){
            sal1.setEditable(true);
            sal2.setEditable(true);
        }
        else{
            sal1.setEditable(false);
            sal2.setEditable(false);
        }
    }//GEN-LAST:event_check3ItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String dbquery = "";
        if(check3.isSelected() && check2.isSelected() && check1.isSelected()) {
            dbquery += " where salary >= "+sal1.getText()+" and salary <= "+sal2.getText()+" and address like '%"+pplace.getText()+"%' and job like '%"+pjob.getText()+"%'";
        } else if(check3.isSelected() && check1.isSelected() && !check2.isSelected()) {
            dbquery += " where salary >= "+sal1.getText()+" and salary <= "+sal2.getText()+" and job like '%"+pjob.getText()+"%'";
        } else if(check3.isSelected() && !check2.isSelected() && !check1.isSelected()) {
            dbquery += " where salary >= "+sal1.getText()+" and salary <= "+sal2.getText();
        } else if(check2.isSelected()&& !check3.isSelected() && !check1.isSelected()) {
            dbquery += " where address like '%"+pplace.getText()+"%'";
        } else if(check1.isSelected() && !check2.isSelected() && !check3.isSelected()) {
            dbquery += " where job like '%"+pjob.getText()+"%'";
        } else if(check3.isSelected() && check2.isSelected() && !check1.isSelected()) {
            dbquery += " where salary >= "+sal1.getText()+" and salary <= "+sal2.getText()+" and address like '%"+pplace.getText()+"%'";
        } else if(check1.isSelected() && check2.isSelected() && !check3.isSelected()) {
            dbquery += " where job like '%"+pjob.getText()+"%' and address like '%"+pplace.getText()+"%'";
        }
        
        System.err.println("select * from vacancies"+dbquery);
        
        try {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from vacancies"+dbquery);
            rs.next();
            DefaultTableModel dtm = (DefaultTableModel) jobdisp.getModel();
            int count = Integer.parseInt(rs.getString("count(*)"));
            dtm.setRowCount(count);
            rs = st.executeQuery("select * from vacancies"+dbquery);
            count = 0;
            while(rs.next()){
                String tcon = "<html><body>"
                        +"<span style='color:#A3B0E4;font-size:11px;font-family:georgia;font-weight:bold;'>"+rs.getString("job")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Job ID: "+rs.getString("jobid")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Company: "+rs.getString("cname")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>"+rs.getString("address")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Salary: "+rs.getString("salary")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>"+rs.getString("vacancies")+" Vacancies</span>"
                        + "</body></html>";
               jobdisp.setValueAt(tcon, count, 0);

                count++;
            }
            
            con.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        new SendMail("('A-S', 'C-S')", FNAME, USRname, 'S').setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel2.setText(FNAME);
        
        try {
            BufferedImage img = ImageIO.read(new File(imgpath));
            Image dimg = img.getScaledInstance(142,148,Image.SCALE_SMOOTH);
            SETDP.setIcon(new ImageIcon(dimg));
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from vacancies");
            rs.next();
            DefaultTableModel dtm = (DefaultTableModel) jobdisp.getModel();
            int count = Integer.parseInt(rs.getString("count(*)"));
            dtm.setRowCount(count);
            rs = st.executeQuery("select * from vacancies");
            count = 0;
            while(rs.next()){
                String tcon = "<html><body>"
                        +"<span style='color:#A3B0E4;font-size:11px;font-family:georgia;font-weight:bold;'>"+rs.getString("job")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Job ID: "+rs.getString("jobid")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Company: "+rs.getString("cname")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>"+rs.getString("address")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>Salary: "+rs.getString("salary")+"</span>"
                        +"<br/><span style='color:black;font-size:10px;font-family:consolas;font-weight:bold;'>"+rs.getString("vacancies")+" Vacancies</span>"
                        + "</body></html>";
               jobdisp.setValueAt(tcon, count, 0);

                count++;
            }
            
            con.close();
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        System.err.println("Window CLosed");
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cps","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from vacancies where jobid='"+jTextField3.getText()+"'");
            rs.next();
            if(!rs.getString("count(*)").equals("0")){
                ResultSet r3 = con.createStatement().executeQuery("select count(*) from appliedjobs where sid=(select sid from student where uname='"+USRname+"') and jobid='"+jTextField3.getText()+"'");
                r3.next();
                System.err.println(r3.getString("count(*)"));
                if(r3.getString("count(*)").equals("0")){
                    st.executeUpdate("insert into appliedjobs values((select sid from student where uname='"+USRname+"'),'"+jTextField3.getText()+"')");
                    JOptionPane.showMessageDialog(path, "Job applied succesfully");
                }else
                    JOptionPane.showMessageDialog(path, "Job is already applied", "Error", 2);
            }else{
                JOptionPane.showMessageDialog(path, "No such job id found!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch1ItemStateChanged
        // TODO add your handling code here:
       if(ch1.isSelected())
           emailid.setEditable(true);
       else
           emailid.setEditable(false);
    }//GEN-LAST:event_ch1ItemStateChanged

    private void ch2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch2ItemStateChanged
        // TODO add your handling code here:
        if(ch2.isSelected())
           phonenumber.setEditable(true);
       else
           phonenumber.setEditable(false);
    }//GEN-LAST:event_ch2ItemStateChanged

    private void ch3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch3ItemStateChanged
        // TODO add your handling code here:
        if(ch3.isSelected()) {
            password.setEditable(true);
            confirmpassword.setEditable(true);
        } else {
            password.setEditable(false);
            confirmpassword.setEditable(false);
        }
    }//GEN-LAST:event_ch3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SETDP;
    private javax.swing.JPanel appjob;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch2;
    private javax.swing.JCheckBox ch3;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField emailid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jobdisp;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel path;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JTextField pjob;
    private javax.swing.JTextField pplace;
    private javax.swing.JLabel profilepic;
    private javax.swing.JPanel pset;
    private javax.swing.JTextField sal1;
    private javax.swing.JTextField sal2;
    private javax.swing.JPanel searchjob;
    private javax.swing.JLabel settime;
    // End of variables declaration//GEN-END:variables
}
